name: Build on master

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

